# Generated by Django 4.0.5 on 2022-06-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'verbose_name_plural': 'Tarefas'},
        ),
    ]
