# Generated by Django 4.0.5 on 2022-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
